apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: shenyu-admin
  labels:
    "app.kubernetes.io/name": shenyu-admin
    "app.kubernetes.io/component": shenyu-admin
    "app.kubernetes.io/instance": shenyu
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/component": shenyu-admin
      "app.kubernetes.io/instance": shenyu
  replicas: 1
  template:
    metadata:
      labels:
        "app.kubernetes.io/name": shenyu-admin
        "app.kubernetes.io/component": shenyu-admin
        "app.kubernetes.io/instance": shenyu
    spec:
      containers:
        - name: shenyu-admin
          image: apache\shenyu-admin:2.4.3
          imagePullPolicy: Always
          ports:
            - containerPort: 9095
          env:
            - name: 'TZ'
              value: 'Asia/Beijing'
          volumeMounts:
          - name: shenyu-admin-config
            mountPath: /opt/shenyu-admin/config/application-h2.yml
            subPath: application-h2.yml
      volumes:
        - name: shenyu-admin-config
          configMap:
            name: shenyu-configmap
            items:
            - key: application-h2.yml
              path: application-h2.yml
