# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.9'

services:
  zookeeper:
    image: zookeeper:3.8.4
    container_name: zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - "31878:2181"
    volumes:
      - ./zoo.cfg
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:2181/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
    restart: always
    networks:
      - shenyu

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "31877:9092"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:9092/actuator/health | grep UP || exit 1" ]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 10s
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

networks:
  shenyu:
    name: shenyu
    driver: bridge
    external: true

