# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: k8s-it

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  k8s-it:
    strategy:
      matrix:
        it: [shenyu-integrated-test-alibaba-dubbo]
        include:
          - it: shenyu-integrated-test-alibaba-dubbo
            save: apache/shenyu-integrated-test-alibaba-dubbo:latest shenyu-examples-alibaba-dubbo-service:latest

    runs-on: ubuntu-latest
    if: (github.repository == 'apache/shenyu')
    steps:
      -
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: install k8s
        run: |
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
      -
        name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.3
      -
        name: install shenyu-admin
        run: |
          cd .. && git clone --branch shenyu-0.1.1 --depth=1 https://github.com/apache/shenyu-helm-chart
          cd shenyu-helm-chart/charts/shenyu
          helm dependency build
          helm install shenyu . --set bootstrap.enabled=false
      -
        name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      -
        uses: actions/setup-java@v1
        with:
          java-version: 8
      -
        name: Build with Maven
        run: ./mvnw -B clean install -Prelease,docker -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
      -
        name: Build examples
        run: ./mvnw -B clean install -Pexample -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -f ./shenyu-examples/pom.xml
      -
        name: Build integrated tests
        run: ./mvnw -B clean install -Pit -DskipTests -f ./shenyu-integrated-test/pom.xml
      -
        name: Build k8s cluster
        run: |
          docker save ${{ matrix.save }} | sudo k3s ctr images import -

          kubectl apply -f ./shenyu-integrated-test/${{ matrix.it }}/k8s/${{ matrix.it }}-deployment.yaml
          kubectl apply -f ./shenyu-integrated-test/${{ matrix.it }}/k8s/${{ matrix.it }}-service.yaml
      -
        name: Wait for docker compose start up completely
        run: |
          bash ./shenyu-integrated-test/${{ matrix.it }}/script/healthcheck.sh
      -
        name: Image test after healthcheck
        run: |
          kubectl get all
          kubectl logs -l app.kubernetes.io/name=shenyu-admin
          kubectl get events --all-namespaces
      -
        name: Run test
        id: test
        run: |
          ./mvnw test -Pit -f ./shenyu-integrated-test/${{ matrix.it }}/pom.xml
        continue-on-error: true
      -
        name: Check test result
        run: |
          kubectl logs -l all=${{ matrix.it }}
